server:
  port: 6666

spring:
  application:
    name: UserService-prod
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/userdb-prod
    username: produser
    password: prodpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
