spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: admin
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 6666
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
user:
  test:
    property: prod-value